services:
  nginx:
    image: nginx:latest
    volumes:
      - ../app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    depends_on:
      - app
    ports:
      - "8088:80"

  app:
    build:
      context: ./app
    volumes:
      - ../app:/var/www
      - ./app/php.ini:/usr/local/etc/php/conf.d/php.ini
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    container_name: ${PROJECT_NAME}-app
    restart: always
    command: >
      sh -c "composer install &&
             chmod -R 777 /var/www/web &&
             chmod -R 777 /var/www/runtime &&
             php-fpm"

  mysql:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}-mysql
    restart: always
#    ports:
#      - "3306:3306"
    volumes:
        - ./mysql-data:/var/lib/mysql
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
    environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  redis:
    image: redis:latest
    container_name: ${PROJECT_NAME}-redis
    restart: always
#    ports:
#      - "6379:6379"
    volumes:
      - ./redis-data:/data
